import { RealtimeChannel } from '@supabase/supabase-js';
import { ActivityLog, Project, ProjectDraft, Task, TaskDraft, TaskStatus, User, UserRole } from '../types';
import { getSupabase } from '../lib/supabase/client';
import { mapActivity, mapProject, mapTask, mapUser, toDb } from '../lib/supabase/mappers';
const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message); };
export const workspaceService = {
  async load() { const db = getSupabase(); const [projects, tasks, users, activity] = await Promise.all([db.from('projects').select('*,project_members(user_id)').order('created_at', { ascending: false }), db.from('tasks').select('*').order('due_date'), db.from('profiles').select('id,email,full_name,role').order('full_name'), db.from('activity_logs').select('*').order('timestamp', { ascending: false }).limit(12)]); [projects.error, tasks.error, users.error, activity.error].forEach(fail); return { projects: (projects.data ?? []).map(mapProject), tasks: (tasks.data ?? []).map(mapTask), users: (users.data ?? []).map(mapUser), activity: (activity.data ?? []).map(mapActivity) }; },
  async saveProject(draft: ProjectDraft, currentUser: User) { const db = getSupabase(); const payload = { name: draft.name, description: draft.description, status: toDb.projectStatus(draft.status), start_date: draft.startDate || null, due_date: draft.dueDate }; let projectId = draft.id; if (projectId) { fail((await db.from('projects').update(payload).eq('id', projectId)).error); } else { const { data, error } = await db.from('projects').insert({ ...payload, created_by: currentUser.id }).select('id').single(); fail(error); projectId = data.id; } const desired = [...new Set([draft.ownerId ?? currentUser.id, ...draft.memberIds])]; const { data: existing, error } = await db.from('project_members').select('user_id').eq('project_id', projectId); fail(error); const ids = (existing ?? []).map(row => row.user_id); const additions = desired.filter(id => !ids.includes(id)).map(user_id => ({ project_id: projectId!, user_id, role: user_id === (draft.ownerId ?? currentUser.id) ? 'owner' : 'member' })); if (additions.length) fail((await db.from('project_members').insert(additions)).error); const removals = ids.filter(id => id !== (draft.ownerId ?? currentUser.id) && !desired.includes(id)); if (removals.length) fail((await db.from('project_members').delete().eq('project_id', projectId).in('user_id', removals)).error); },
  async deleteProject(id: string) { fail((await getSupabase().from('projects').delete().eq('id', id)).error); },
  async saveTask(draft: TaskDraft, currentUser: User) { const payload = { project_id: draft.projectId, title: draft.title, description: draft.description, assigned_to: draft.assigneeId, status: toDb.taskStatus(draft.status), priority: toDb.priority(draft.priority), due_date: draft.dueDate, task_work_log: draft.workLog || '' }; const result = draft.id ? await getSupabase().from('tasks').update(payload).eq('id', draft.id) : await getSupabase().from('tasks').insert({ ...payload, created_by: currentUser.id }); fail(result.error); },
  async updateTaskStatus(id: string, status: TaskStatus, workLog: string) { fail((await getSupabase().from('tasks').update({ status: toDb.taskStatus(status), task_work_log: workLog }).eq('id', id)).error); },
  async deleteTask(id: string) { fail((await getSupabase().from('tasks').delete().eq('id', id)).error); },
  async updateMemberRole(email: string, role: UserRole) { const { error } = await getSupabase().from('profiles').update({ role: role.toLowerCase() }).eq('email', email); fail(error); },
  subscribe(onChange: () => void): RealtimeChannel { return getSupabase().channel('zentask-workspace').on('postgres_changes', { event: '*', schema: 'public', table: 'projects' }, onChange).on('postgres_changes', { event: '*', schema: 'public', table: 'project_members' }, onChange).on('postgres_changes', { event: '*', schema: 'public', table: 'tasks' }, onChange).subscribe(); },
  unsubscribe(channel: RealtimeChannel) { return getSupabase().removeChannel(channel); },
};
